[package]
name = "b64url"
version = "0.1.0"
authors = ["Kenneth Wang Pedersen <kenneth@wangpedersen.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"
base64 = "0.13.0"
